<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Dekorras.Application\Dekorras.Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Dekorras.Persistence\Dekorras.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Dekorras.Infrastructure\Dekorras.Infrastructure.csproj" />
  </ItemGroup>

</Project>
