<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Dekorras.Application\Dekorras.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Dekorras.Persistence\Dekorras.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Dekorras.Infrastructure\Dekorras.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
